force-app/main/default/objects/Lane_Price__c/Lane_Price__c.object-meta.xml
<CustomObject>
    <label>Lane Price</label>
    <nameField>
        <displayFormat>LP-{0000000}</displayFormat>
        <label>Lane Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lane Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lane_Price__c/fields/Lane__c.field-meta.xml
<CustomField>
    <fullName>Lane__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lane</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lane Prices</relationshipLabel>
    <relationshipName>Lane_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mandatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Price_Request__c.field-meta.xml
<CustomField>
    <fullName>Price_Request__c</fullName>
    <label>Price Request</label>
    <referenceTo>Price_Request__c</referenceTo>
    <relationshipLabel>Lane Prices</relationshipLabel>
    <relationshipName>Lane_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Type_Of_Trailer__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Trailer__c</fullName>
    <label>Type Of Trailer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dual temp</fullName>
            </value>
            <value>
                <fullName>Frigo - ambient</fullName>
            </value>
            <value>
                <fullName>Frigo - chilled</fullName>
            </value>
            <value>
                <fullName>Frigo - frozen</fullName>
            </value>
            <value>
                <fullName>Frigo - split wall</fullName>
            </value>
            <value>
                <fullName>Curtainside - ambient</fullName>
            </value>
            <value>
                <fullName>Box trailer</fullName>
            </value>
            <value>
                <fullName>Cooled</fullName>
                <isActive>false</isActive>
                <label>Cooled</label>
            </value>
            <value>
                <fullName>Dual-temp</fullName>
                <isActive>false</isActive>
                <label>Dual-temp</label>
            </value>
            <value>
                <fullName>Frigo</fullName>
                <isActive>false</isActive>
                <label>Frigo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Request__c/Price_Request__c.object-meta.xml
<CustomObject>
    <label>Price Request</label>
    <nameField>
        <label>Price Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Request__c/fields/Type_of_trailer__c.field-meta.xml
<CustomField>
    <fullName>Type_of_trailer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Type of trailer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TPQAddLanesToPriceRequestAction.cls
public with sharing class TPQAddLanesToPriceRequestAction {
    private static final String DEFAULT_CURRENCY = 'EUR';
    private static final String DELIMITER = ';';

    public class Input {
        @InvocableVariable(required=true)
        public Id priceRequestId;
       
        @InvocableVariable(required=true)
        public List<String> filteredLaneIds;

        @InvocableVariable
        public List<String> mandatoryLaneIds;

        @InvocableVariable(required=true)
        public String trailerTypesString;
    }

    @InvocableMethod(label='TPQ Add Lanes To Price Request' description='TPQ Add Lanes To Price Request')
    public static void addLanesToPriceRequest(List<Input> inputs)
    {    
        if (inputs == null || inputs.isEmpty()) {
            System.debug(LoggingLevel.ERROR, 'No input data provided to run TPQ Add Lanes To Price Request');
            return;
        }
        
        try
        {
            Input req = inputs[0];
            List<Lane_Price__c> lanePricesToInsert = new List<Lane_Price__c>();
            List<String> filteredLaneIds = req.filteredLaneIds;
            List<String> mandatoryLaneIds = req.mandatoryLaneIds == null ? new List<String>() : req.mandatoryLaneIds;
            List<String> trailerTypesList = req.trailerTypesString.split(DELIMITER);

            if (trailerTypesList.isEmpty()) {
                // Create lane prices without trailer types
                for (String productId : filteredLaneIds) {
                    lanePricesToInsert.add(
                        new Lane_Price__c(
                            Lane__c = productId,
                            Price_Request__c = req.priceRequestId,
                            Mandatory__c = mandatoryLaneIds.contains(productId) ? true : false,
                            CurrencyIsoCode = DEFAULT_CURRENCY
                        )
                    );           
                }
            } else {            
                for (String trailerType : trailerTypesList) {
                    for (String productId : filteredLaneIds) {
                        lanePricesToInsert.add(
                            new Lane_Price__c(
                                Lane__c = productId,
                                Price_Request__c = req.priceRequestId,
                                Type_Of_Trailer__c = trailerType,
                                Mandatory__c = mandatoryLaneIds.contains(productId) ? true : false,
                                CurrencyIsoCode = DEFAULT_CURRENCY
                            )
                        );
                    }
                }
            }

            if (!lanePricesToInsert.isEmpty()) insert lanePricesToInsert;

        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, 'Error in TPQ Add Lanes To Price Request: ' + e.getMessage());
            throw e;
        }

        return;
    }
}