force-app/main/default/objects/Price_Request__c/Price_Request__c.object-meta.xml
<CustomObject>
    <label>Price Request</label>
    <nameField>
        <label>Price Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Request__c/fields/Contacts_emails__c.field-meta.xml
<CustomField>
    <fullName>Contacts_emails__c</fullName>
    <label>Contacts&apos; emails</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Portal_URL__c.field-meta.xml
<CustomField>
    <fullName>Portal_URL__c</fullName>
    <label>Portal URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Answer pending</fullName>
            </value>
            <value>
                <fullName>Answer received</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PriceRequestTriggerHandler.cls
public with sharing class PriceRequestTriggerHandler {
    
    public static void sendEmailToContact(Map<Id, Price_Request__c> newMap, Map<Id, Price_Request__c> oldMap){
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();

        Id orgWideEmailId = getOrgWideEmailAddressId();

        for(Price_Request__c pr : newMap.values()){
            if(oldMap != null && oldMap.containsKey(pr.Id) && (oldMap.get(pr.Id).Stage__c == 'Answer received' || oldMap.get(pr.Id).Stage__c == 'Completed')
             && pr.Stage__c == 'Answer pending' && pr.Contacts_emails__c != null){
                
                List<String> listEmailToSend = pr.Contacts_emails__c.split(';');

                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setToAddresses(listEmailToSend);
                mail.setSubject('Your request for a price update has been approved');

                if(orgWideEmailId != null) {mail.setOrgWideEmailAddressId(orgWideEmailId);}

                String portalUrl = pr.Portal_URL__c != null ? pr.Portal_URL__c.trim() : '';
                String body = 
                    'Dear Sir/Madam,\n\n' +
                    'We hope this message finds you well.\n\n' +
                    'Your request has been approved. You can now make changes to your submitted freight prices in the portal at your convenience.\n\n' +
                    'Portal access link:\n' +
                    (portalUrl != '' ? portalUrl + '\n\n' : '\n') +
                    'If you have any questions or experience any issues accessing the portal, please don’t hesitate to contact us.\n\n' +
                    'Thank you for your prompt attention to this update.\n\n' +
                    'Best regards,\n\n' +
                    'The ECL Team';

                mail.setPlainTextBody(body);
                mails.add(mail);
            }
        }
        if(!mails.isEmpty()) {
            try {
                Messaging.sendEmail(mails);
            } catch (Exception e) {
                System.debug('Error sending PriceRequest emails: ' + e);
            }
        }
    }

    private static Id getOrgWideEmailAddressId() {
        try {            
            OrgWideEmailAddress[] oweaFallback = [
                SELECT Id 
                FROM OrgWideEmailAddress 
                LIMIT 1
            ];
            
            return !oweaFallback.isEmpty() ? oweaFallback[0].Id : null;
            
        } catch (Exception e) {
            System.debug('Error retrieving Organization-Wide Email Address: ' + e);
            return null;
        }
    }

}