force-app/main/default/objects/Account/fields/Access_code__c.field-meta.xml
<CustomField>
    <fullName>Access_code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <inlineHelpText>The max length is 15 characters</inlineHelpText>
    <label>Portal Access Code</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Destination_Country_Codes__c.field-meta.xml
<CustomField>
    <fullName>Destination_Country_Codes__c</fullName>
    <label>Destination Country Codes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Trailer_Types__c.field-meta.xml
<CustomField>
    <fullName>Trailer_Types__c</fullName>
    <label>Trailer Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dual temp</fullName>
            </value>
            <value>
                <fullName>Frigo - ambient</fullName>
            </value>
            <value>
                <fullName>Frigo - chilled</fullName>
            </value>
            <value>
                <fullName>Frigo - frozen</fullName>
            </value>
            <value>
                <fullName>Frigo - split wall</fullName>
            </value>
            <value>
                <fullName>Curtainside - ambient</fullName>
            </value>
            <value>
                <fullName>Box trailer</fullName>
            </value>
            <value>
                <fullName>Cooled</fullName>
                <isActive>false</isActive>
                <label>Cooled</label>
            </value>
            <value>
                <fullName>Dual-temp</fullName>
                <isActive>false</isActive>
                <label>Dual-temp</label>
            </value>
            <value>
                <fullName>Frigo</fullName>
                <isActive>false</isActive>
                <label>Frigo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lane_Price__c/Lane_Price__c.object-meta.xml
<CustomObject>
    <label>Lane Price</label>
    <nameField>
        <displayFormat>LP-{0000000}</displayFormat>
        <label>Lane Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lane Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lane_Price__c/fields/Freight_Price__c.field-meta.xml
<CustomField>
    <fullName>Freight_Price__c</fullName>
    <label>€ Lane Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Lane__c.field-meta.xml
<CustomField>
    <fullName>Lane__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lane</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lane Prices</relationshipLabel>
    <relationshipName>Lane_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mandatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Price_Request__c.field-meta.xml
<CustomField>
    <fullName>Price_Request__c</fullName>
    <label>Price Request</label>
    <referenceTo>Price_Request__c</referenceTo>
    <relationshipLabel>Lane Prices</relationshipLabel>
    <relationshipName>Lane_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Type_Of_Trailer__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Trailer__c</fullName>
    <label>Type Of Trailer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dual temp</fullName>
            </value>
            <value>
                <fullName>Frigo - ambient</fullName>
            </value>
            <value>
                <fullName>Frigo - chilled</fullName>
            </value>
            <value>
                <fullName>Frigo - frozen</fullName>
            </value>
            <value>
                <fullName>Frigo - split wall</fullName>
            </value>
            <value>
                <fullName>Curtainside - ambient</fullName>
            </value>
            <value>
                <fullName>Box trailer</fullName>
            </value>
            <value>
                <fullName>Cooled</fullName>
                <isActive>false</isActive>
                <label>Cooled</label>
            </value>
            <value>
                <fullName>Dual-temp</fullName>
                <isActive>false</isActive>
                <label>Dual-temp</label>
            </value>
            <value>
                <fullName>Frigo</fullName>
                <isActive>false</isActive>
                <label>Frigo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loading</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Request__c/Price_Request__c.object-meta.xml
<CustomObject>
    <label>Price Request</label>
    <nameField>
        <label>Price Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Requests (Account)</relationshipLabel>
    <relationshipName>Price_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Loading_Location__c.field-meta.xml
<CustomField>
    <fullName>Loading_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loading Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.Type__c</field>
            <operation>equals</operation>
            <value>Loading</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Price Requests (Loading Location)</relationshipLabel>
    <relationshipName>Loading_Price_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Answer pending</fullName>
            </value>
            <value>
                <fullName>Answer received</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Type_of_trailer__c.field-meta.xml
<CustomField>
    <fullName>Type_of_trailer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Type of trailer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Destination_Location__c.field-meta.xml
<CustomField>
    <fullName>Destination_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.Type__c</field>
            <operation>equals</operation>
            <value>Delivery</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Products (Destination Location)</relationshipLabel>
    <relationshipName>Destinations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Loading_Location__c.field-meta.xml
<CustomField>
    <fullName>Loading_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loading Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.Type__c</field>
            <operation>equals</operation>
            <value>Loading</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Loadings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Country_ISO_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DK</fullName>
    </customValue>
    <customValue>
        <fullName>GB</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IS</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>GI</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>CY</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>MC</fullName>
    </customValue>
    <customValue>
        <fullName>RS</fullName>
    </customValue>
    <masterLabel>Country ISO Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TPQGetLanesToAddInPriceRequestTest.cls
@isTest
private class TPQGetLanesToAddInPriceRequestTest {

    @TestSetup
    static void setupTestData() {

        Account testAccount = new Account(
            Name = 'Test Carrier Account',
            Type = 'Carrier',
            Trailer_Types__c = 'Dual temp;Frigo - chilled',
            Destination_Country_Codes__c = 'NL;DE;FR',
            Access_code__c = 'NMMNBB6778'
        );
        insert testAccount;
        
        List<Location__c> locations = new List<Location__c>{
            new Location__c(
                Name = 'NL Loading Location',
                Type__c = 'Loading',
                Country_Code__c = 'NL',
                Postal_Code__c = '1234AB'
            ),
            new Location__c(
                Name = 'DE Loading Location',
                Type__c = 'Loading',
                Country_Code__c = 'DE',
                Postal_Code__c = '12345'
            ),
            new Location__c(
                Name = 'FR Delivery Location',
                Type__c = 'Delivery',
                Country_Code__c = 'FR',
                Postal_Code__c = '75001'
            ),
            new Location__c(
                Name = 'DE Delivery Location',
                Type__c = 'Delivery',
                Country_Code__c = 'DE',
                Postal_Code__c = '54321'
            ),
            new Location__c(
                Name = 'NL Delivery Location',
                Type__c = 'Delivery',
                Country_Code__c = 'NL',
                Postal_Code__c = '5678CD'
            ),
            new Location__c(
                Name = 'BE Delivery Location',
                Type__c = 'Delivery',
                Country_Code__c = 'BE',
                Postal_Code__c = '1000'
            )
        };
        insert locations;
        
        List<Product2> lanes = new List<Product2>{
            new Product2(
                Name = 'NL-FR Lane',
                Loading_Location__c = locations[0].Id,
                Destination_Location__c = locations[2].Id,
                IsActive = true
            ),
            new Product2(
                Name = 'NL-DE Lane',
                Loading_Location__c = locations[0].Id,
                Destination_Location__c = locations[3].Id,
                IsActive = true
            ),
            new Product2(
                Name = 'DE-FR Lane',
                Loading_Location__c = locations[1].Id,
                Destination_Location__c = locations[2].Id,
                IsActive = true
            ),
            new Product2(
                Name = 'DE-NL Lane',
                Loading_Location__c = locations[1].Id,
                Destination_Location__c = locations[4].Id,
                IsActive = true
            ),
            new Product2(
                Name = 'NL-BE Lane',
                Loading_Location__c = locations[0].Id,
                Destination_Location__c = locations[5].Id,
                IsActive = true
            )
        };
        insert lanes;
        
        Price_Request__c priceRequest = new Price_Request__c(
            Name = 'Test Price Request',
            Account__c = testAccount.Id,
            Request_Date__c = Date.today(),
            Stage__c = 'Answer received'
        );
        insert priceRequest;
        
        // Create existing lane price (NL-FR Lane already exists in price request)
        Lane_Price__c existingLanePrice = new Lane_Price__c(
            Price_Request__c = priceRequest.Id,
            Lane__c = lanes[0].Id,
            Type_Of_Trailer__c = 'Dual temp',
            Freight_Price__c = 1000,
            Mandatory__c = true,
            CurrencyIsoCode = 'EUR'
        );
        insert existingLanePrice;
    }
    
    @isTest
    static void testGetMatchingLanesSuccessfully() {
        Price_Request__c priceRequest = [SELECT Id FROM Price_Request__c LIMIT 1];
        
        TPQGetLanesToAddInPriceRequest.Input input = new TPQGetLanesToAddInPriceRequest.Input();
        input.priceRequestId = priceRequest.Id;
        input.loadingCountryCodes = new List<String>{ 'NL;DE' };
        input.deliveryCountryCodes = new List<String>{ 'FR;DE' };
        
        Test.startTest();
        List<TPQGetLanesToAddInPriceRequest.Response> response = TPQGetLanesToAddInPriceRequest.addLanesToPriceRequest(
            new List<TPQGetLanesToAddInPriceRequest.Input>{ input }
        );
        Test.stopTest();
        
        Assert.areEqual(1, response.size(), 'Should return one response');
        Assert.isNotNull(response[0].matchingLanes, 'Matching lanes should not be null');
        Assert.areEqual(2, response[0].matchingLanes.size(), 'Should return 2 matching lanes');
        
        Set<String> laneNames = new Set<String>();
        for (Product2 lane : response[0].matchingLanes) {
            laneNames.add(lane.Name);
        }

        Assert.isTrue(laneNames.contains('NL-DE Lane'), 'Should include NL-DE Lane');
        Assert.isTrue(laneNames.contains('DE-FR Lane'), 'Should include DE-FR Lane');
        Assert.isFalse(laneNames.contains('DE-NL Lane'), 'Should exclude DE-NL Lane (NL not in delivery codes)');
        Assert.isFalse(laneNames.contains('NL-FR Lane'), 'Should exclude existing NL-FR Lane');
        Assert.isFalse(laneNames.contains('NL-BE Lane'), 'Should exclude NL-BE Lane (BE not in delivery codes)');
    }
    
    @isTest
    static void testGetLanesWithSingleCountryCodes() {
        Price_Request__c priceRequest = [SELECT Id FROM Price_Request__c LIMIT 1];
        
        TPQGetLanesToAddInPriceRequest.Input input = new TPQGetLanesToAddInPriceRequest.Input();
        input.priceRequestId = priceRequest.Id;
        input.loadingCountryCodes = new List<String>{ 'NL' };
        input.deliveryCountryCodes = new List<String>{ 'DE' };
        
        Test.startTest();
        List<TPQGetLanesToAddInPriceRequest.Response> response = TPQGetLanesToAddInPriceRequest.addLanesToPriceRequest(
            new List<TPQGetLanesToAddInPriceRequest.Input>{ input }
        );
        Test.stopTest();
        
        Assert.areEqual(1, response.size(), 'Should return one response');
        Assert.areEqual(1, response[0].matchingLanes.size(), 'Should return 1 matching lane');
        Assert.areEqual('NL-DE Lane', response[0].matchingLanes[0].Name, 'Should return NL-DE Lane');
    }
    
    @isTest
    static void testGetLanesWithNoMatchingCountryCodes() {
        Price_Request__c priceRequest = [SELECT Id FROM Price_Request__c LIMIT 1];
        
        TPQGetLanesToAddInPriceRequest.Input input = new TPQGetLanesToAddInPriceRequest.Input();
        input.priceRequestId = priceRequest.Id;
        input.loadingCountryCodes = new List<String>{ 'ES' };
        input.deliveryCountryCodes = new List<String>{ 'IT' };
        
        Test.startTest();
        List<TPQGetLanesToAddInPriceRequest.Response> response = TPQGetLanesToAddInPriceRequest.addLanesToPriceRequest(
            new List<TPQGetLanesToAddInPriceRequest.Input>{ input }
        );
        Test.stopTest();
        
        Assert.areEqual(1, response.size(), 'Should return one response');
        Assert.areEqual(0, response[0].matchingLanes.size(), 'Should return 0 matching lanes');
    }
    
    @isTest
    static void testGetLanesWithInvalidInput() {
        Test.startTest();
        
        // Test null input list
        List<TPQGetLanesToAddInPriceRequest.Response> nullResponse = TPQGetLanesToAddInPriceRequest.addLanesToPriceRequest(null);
        Assert.areEqual(0, nullResponse.size(), 'Should handle null input');
        
        // Test empty input list
        List<TPQGetLanesToAddInPriceRequest.Response> emptyResponse = TPQGetLanesToAddInPriceRequest.addLanesToPriceRequest(
            new List<TPQGetLanesToAddInPriceRequest.Input>()
        );
        Assert.areEqual(0, emptyResponse.size(), 'Should handle empty input list');
        
        Test.stopTest();
    }
    
    @isTest
    static void testParseCountryCodesWithVariousFormats() {
        Test.startTest();
        
        // Test with semicolon-separated values
        List<String> result1 = TPQGetLanesToAddInPriceRequest.parseCountryCodes(new List<String>{ 'NL;DE;FR' });
        Assert.areEqual(3, result1.size(), 'Should parse 3 country codes');
        Assert.isTrue(result1.contains('NL'), 'Should contain NL');
        Assert.isTrue(result1.contains('DE'), 'Should contain DE');
        Assert.isTrue(result1.contains('FR'), 'Should contain FR');
        
        // Test with multiple list items
        List<String> result2 = TPQGetLanesToAddInPriceRequest.parseCountryCodes(new List<String>{ 'NL;DE', 'FR;BE' });
        Assert.areEqual(4, result2.size(), 'Should parse 4 country codes');
        
        // Test with spaces
        List<String> result3 = TPQGetLanesToAddInPriceRequest.parseCountryCodes(new List<String>{ ' NL ; DE ' });
        Assert.areEqual(2, result3.size(), 'Should parse 2 country codes and trim spaces');
        
        // Test with empty strings
        List<String> result4 = TPQGetLanesToAddInPriceRequest.parseCountryCodes(new List<String>{ '', 'NL', '' });
        Assert.areEqual(1, result4.size(), 'Should skip empty strings');
        Assert.areEqual('NL', result4[0], 'Should only return NL');
        
        // Test with null
        List<String> result5 = TPQGetLanesToAddInPriceRequest.parseCountryCodes(null);
        Assert.areEqual(0, result5.size(), 'Should handle null input');
        
        // Test with blank values
        List<String> result6 = TPQGetLanesToAddInPriceRequest.parseCountryCodes(new List<String>{ ';;NL;;' });
        Assert.areEqual(1, result6.size(), 'Should skip blank values');
        Assert.areEqual('NL', result6[0], 'Should only return NL');
        
        Test.stopTest();
    }
    
    @isTest
    static void testGetLanesExcludesExistingLanes() {
        Price_Request__c priceRequest = [SELECT Id FROM Price_Request__c LIMIT 1];
        Product2 existingLane = [SELECT Id FROM Product2 WHERE Name = 'NL-FR Lane' LIMIT 1];
        
        TPQGetLanesToAddInPriceRequest.Input input = new TPQGetLanesToAddInPriceRequest.Input();
        input.priceRequestId = priceRequest.Id;
        input.loadingCountryCodes = new List<String>{ 'NL' };
        input.deliveryCountryCodes = new List<String>{ 'FR;DE' };
        
        Test.startTest();
        List<TPQGetLanesToAddInPriceRequest.Response> response = TPQGetLanesToAddInPriceRequest.addLanesToPriceRequest(
            new List<TPQGetLanesToAddInPriceRequest.Input>{ input }
        );
        Test.stopTest();
        
        Assert.areEqual(1, response.size(), 'Should return one response');
        
        Set<Id> returnedLaneIds = new Set<Id>();
        for (Product2 lane : response[0].matchingLanes) {
            returnedLaneIds.add(lane.Id);
        }
        
        Assert.isFalse(returnedLaneIds.contains(existingLane.Id), 'Should exclude existing lane (NL-FR)');
        Assert.areEqual(1, response[0].matchingLanes.size(), 'Should only return NL-DE Lane');
    }
}