force-app/main/default/objects/Account/fields/Access_code__c.field-meta.xml
<CustomField>
    <fullName>Access_code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <inlineHelpText>The max length is 15 characters</inlineHelpText>
    <label>Portal Access Code</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Destination_Country_Codes__c.field-meta.xml
<CustomField>
    <fullName>Destination_Country_Codes__c</fullName>
    <label>Destination Country Codes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Trailer_Types__c.field-meta.xml
<CustomField>
    <fullName>Trailer_Types__c</fullName>
    <label>Trailer Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dual temp</fullName>
            </value>
            <value>
                <fullName>Frigo - ambient</fullName>
            </value>
            <value>
                <fullName>Frigo - chilled</fullName>
            </value>
            <value>
                <fullName>Frigo - frozen</fullName>
            </value>
            <value>
                <fullName>Frigo - split wall</fullName>
            </value>
            <value>
                <fullName>Curtainside - ambient</fullName>
            </value>
            <value>
                <fullName>Box trailer</fullName>
            </value>
            <value>
                <fullName>Cooled</fullName>
                <isActive>false</isActive>
                <label>Cooled</label>
            </value>
            <value>
                <fullName>Dual-temp</fullName>
                <isActive>false</isActive>
                <label>Dual-temp</label>
            </value>
            <value>
                <fullName>Frigo</fullName>
                <isActive>false</isActive>
                <label>Frigo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lane_Price__c/Lane_Price__c.object-meta.xml
<CustomObject>
    <label>Lane Price</label>
    <nameField>
        <displayFormat>LP-{0000000}</displayFormat>
        <label>Lane Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lane Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lane_Price__c/fields/Lane__c.field-meta.xml
<CustomField>
    <fullName>Lane__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lane</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lane Prices</relationshipLabel>
    <relationshipName>Lane_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mandatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Price_Request__c.field-meta.xml
<CustomField>
    <fullName>Price_Request__c</fullName>
    <label>Price Request</label>
    <referenceTo>Price_Request__c</referenceTo>
    <relationshipLabel>Lane Prices</relationshipLabel>
    <relationshipName>Lane_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Type_Of_Trailer__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Trailer__c</fullName>
    <label>Type Of Trailer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dual temp</fullName>
            </value>
            <value>
                <fullName>Frigo - ambient</fullName>
            </value>
            <value>
                <fullName>Frigo - chilled</fullName>
            </value>
            <value>
                <fullName>Frigo - frozen</fullName>
            </value>
            <value>
                <fullName>Frigo - split wall</fullName>
            </value>
            <value>
                <fullName>Curtainside - ambient</fullName>
            </value>
            <value>
                <fullName>Box trailer</fullName>
            </value>
            <value>
                <fullName>Cooled</fullName>
                <isActive>false</isActive>
                <label>Cooled</label>
            </value>
            <value>
                <fullName>Dual-temp</fullName>
                <isActive>false</isActive>
                <label>Dual-temp</label>
            </value>
            <value>
                <fullName>Frigo</fullName>
                <isActive>false</isActive>
                <label>Frigo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loading</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Request__c/Price_Request__c.object-meta.xml
<CustomObject>
    <label>Price Request</label>
    <nameField>
        <label>Price Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Requests (Account)</relationshipLabel>
    <relationshipName>Price_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Loading_Location__c.field-meta.xml
<CustomField>
    <fullName>Loading_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loading Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.Type__c</field>
            <operation>equals</operation>
            <value>Loading</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Price Requests (Loading Location)</relationshipLabel>
    <relationshipName>Loading_Price_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Answer pending</fullName>
            </value>
            <value>
                <fullName>Answer received</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Type_of_trailer__c.field-meta.xml
<CustomField>
    <fullName>Type_of_trailer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Type of trailer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Destination_Location__c.field-meta.xml
<CustomField>
    <fullName>Destination_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.Type__c</field>
            <operation>equals</operation>
            <value>Delivery</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Products (Destination Location)</relationshipLabel>
    <relationshipName>Destinations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Loading_Location__c.field-meta.xml
<CustomField>
    <fullName>Loading_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loading Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.Type__c</field>
            <operation>equals</operation>
            <value>Loading</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Loadings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Country_ISO_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DK</fullName>
    </customValue>
    <customValue>
        <fullName>GB</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IS</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>GI</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>CY</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>MC</fullName>
    </customValue>
    <customValue>
        <fullName>RS</fullName>
    </customValue>
    <masterLabel>Country ISO Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TPQAddLanesToPriceRequestActionTest.cls
@isTest
private class TPQAddLanesToPriceRequestActionTest {
    @TestSetup
    static void setupTestData() {

        Account testAccount = new Account(
            Name = 'Test Carrier Account',
            Type = 'Carrier',
            Trailer_Types__c = 'Dual temp;Frigo - chilled',
            Destination_Country_Codes__c = 'NL;DE;FR',
            Access_code__c = 'NMMNBB6778'
        );
        insert testAccount;
        
        List<Location__c> locations = new List<Location__c>{
            new Location__c(
                Name = 'NL Loading Location',
                Type__c = 'Loading',
                Country_Code__c = 'NL',
                Postal_Code__c = '1234AB'
            ),
            new Location__c(
                Name = 'FR Delivery Location',
                Type__c = 'Delivery',
                Country_Code__c = 'FR',
                Postal_Code__c = '75001'
            ),
            new Location__c(
                Name = 'DE Delivery Location',
                Type__c = 'Delivery',
                Country_Code__c = 'DE',
                Postal_Code__c = '54321'
            )
        };
        insert locations;
        
        List<Product2> lanes = new List<Product2>{
            new Product2(
                Name = 'NL-FR Lane',
                Loading_Location__c = locations[0].Id,
                Destination_Location__c = locations[1].Id,
                IsActive = true
            ),
            new Product2(
                Name = 'NL-DE Lane',
                Loading_Location__c = locations[0].Id,
                Destination_Location__c = locations[2].Id,
                IsActive = true
            )
        };
        insert lanes;
        
        Price_Request__c priceRequest = new Price_Request__c(
            Name = 'Test Price Request',
            Account__c = testAccount.Id,
            Request_Date__c = Date.today(),
            Stage__c = 'Answer received',
            CurrencyIsoCode = 'EUR'
        );
        insert priceRequest;
    }
    
    @isTest
    static void testAddLanesWithMultipleTrailerTypes() {
        Price_Request__c priceRequest = [SELECT Id FROM Price_Request__c LIMIT 1];
        List<Product2> lanes = [SELECT Id FROM Product2];
        
        List<String> laneIds = new List<String>();
        for (Product2 lane : lanes) {
            laneIds.add(lane.Id);
        }
        
        TPQAddLanesToPriceRequestAction.Input input = new TPQAddLanesToPriceRequestAction.Input();
        input.priceRequestId = priceRequest.Id;
        input.filteredLaneIds = laneIds;
        input.mandatoryLaneIds = new List<String>{ lanes[0].Id };
        input.trailerTypesString = 'Dual temp;Frigo - chilled';
        
        Test.startTest();
        TPQAddLanesToPriceRequestAction.addLanesToPriceRequest(
            new List<TPQAddLanesToPriceRequestAction.Input>{ input }
        );
        Test.stopTest();
        
        List<Lane_Price__c> lanePrices = [
            SELECT Id, Lane__c, Type_Of_Trailer__c, Mandatory__c, CurrencyIsoCode, Price_Request__c
            FROM Lane_Price__c
            WHERE Price_Request__c = :priceRequest.Id
        ];
        
        Assert.areEqual(4, lanePrices.size(), 'Should create 4 lane prices (2 lanes x 2 trailer types)');
        
        Integer mandatoryCount = 0;
        Integer nonMandatoryCount = 0;
        Set<String> trailerTypes = new Set<String>();
        
        for (Lane_Price__c lp : lanePrices) {
            Assert.areEqual(priceRequest.Id, lp.Price_Request__c, 'Should be linked to price request');
            Assert.areEqual('EUR', lp.CurrencyIsoCode, 'Should have EUR currency');
            Assert.isNotNull(lp.Type_Of_Trailer__c, 'Should have trailer type');
            trailerTypes.add(lp.Type_Of_Trailer__c);
            
            if (lp.Lane__c == lanes[0].Id) {
                Assert.isTrue(lp.Mandatory__c, 'First lane should be mandatory');
                mandatoryCount++;
            } else {
                Assert.isFalse(lp.Mandatory__c, 'Second lane should not be mandatory');
                nonMandatoryCount++;
            }
        }
        
        Assert.areEqual(2, mandatoryCount, 'Should have 2 mandatory lane prices');
        Assert.areEqual(2, nonMandatoryCount, 'Should have 2 non-mandatory lane prices');
        Assert.isTrue(trailerTypes.contains('Dual temp'), 'Should contain Dual temp');
        Assert.isTrue(trailerTypes.contains('Frigo - chilled'), 'Should contain Frigo - chilled');
    }
    
    @isTest
    static void testAddLanesWithoutTrailerTypes() {
        Price_Request__c priceRequest = [SELECT Id FROM Price_Request__c LIMIT 1];
        List<Product2> lanes = [SELECT Id FROM Product2 ORDER BY Name LIMIT 1];
        
        TPQAddLanesToPriceRequestAction.Input input = new TPQAddLanesToPriceRequestAction.Input();
        input.priceRequestId = priceRequest.Id;
        input.filteredLaneIds = new List<String>{ lanes[0].Id };
        input.mandatoryLaneIds = new List<String>{ lanes[0].Id };
        input.trailerTypesString = '';
        
        Test.startTest();
        TPQAddLanesToPriceRequestAction.addLanesToPriceRequest(
            new List<TPQAddLanesToPriceRequestAction.Input>{ input }
        );
        Test.stopTest();
        
        List<Lane_Price__c> lanePrices = [
            SELECT Id, Type_Of_Trailer__c, Mandatory__c, CurrencyIsoCode
            FROM Lane_Price__c
            WHERE Price_Request__c = :priceRequest.Id
        ];
        
        Assert.areEqual(1, lanePrices.size(), 'Should create 1 lane price');
        Assert.isNull(lanePrices[0].Type_Of_Trailer__c, 'Should not have trailer type');
        Assert.isTrue(lanePrices[0].Mandatory__c, 'Should be mandatory');
        Assert.areEqual('EUR', lanePrices[0].CurrencyIsoCode, 'Should have EUR currency');
    }
    
    @isTest
    static void testAddLanesWithAllMandatory() {
        Price_Request__c priceRequest = [SELECT Id FROM Price_Request__c LIMIT 1];
        List<Product2> lanes = [SELECT Id FROM Product2];
        
        List<String> laneIds = new List<String>();
        for (Product2 lane : lanes) {
            laneIds.add(lane.Id);
        }
        
        TPQAddLanesToPriceRequestAction.Input input = new TPQAddLanesToPriceRequestAction.Input();
        input.priceRequestId = priceRequest.Id;
        input.filteredLaneIds = laneIds;
        input.mandatoryLaneIds = laneIds;
        input.trailerTypesString = 'Dual temp';
        
        Test.startTest();
        TPQAddLanesToPriceRequestAction.addLanesToPriceRequest(
            new List<TPQAddLanesToPriceRequestAction.Input>{ input }
        );
        Test.stopTest();
        
        List<Lane_Price__c> lanePrices = [
            SELECT Id, Mandatory__c
            FROM Lane_Price__c
            WHERE Price_Request__c = :priceRequest.Id
        ];
        
        Assert.areEqual(2, lanePrices.size(), 'Should create 2 lane prices');
        
        for (Lane_Price__c lp : lanePrices) {
            Assert.isTrue(lp.Mandatory__c, 'All lanes should be mandatory');
        }
    }
    
    @isTest
    static void testAddLanesWithInvalidInput() {
        Test.startTest();
        
        // Test null input list
        TPQAddLanesToPriceRequestAction.addLanesToPriceRequest(null);
        
        // Test empty input list
        TPQAddLanesToPriceRequestAction.addLanesToPriceRequest(
            new List<TPQAddLanesToPriceRequestAction.Input>()
        );
        
        Test.stopTest();
        
        // Verify no lane prices were created
        List<Lane_Price__c> lanePrices = [SELECT Id FROM Lane_Price__c];
        Assert.areEqual(0, lanePrices.size(), 'Should not create any lane prices with invalid input');
    }
    
    @isTest
    static void testAddLanesWithExceptionHandling() {
        TPQAddLanesToPriceRequestAction.Input input = new TPQAddLanesToPriceRequestAction.Input();
        input.priceRequestId = null;
        input.filteredLaneIds = new List<String>{ 'invalidId' };
        input.mandatoryLaneIds = new List<String>();
        input.trailerTypesString = 'Dual temp';
        
        Test.startTest();
        try {
            TPQAddLanesToPriceRequestAction.addLanesToPriceRequest(
                new List<TPQAddLanesToPriceRequestAction.Input>{ input }
            );
            Assert.fail('Should have thrown an exception');
        } catch (Exception e) {
            Assert.isNotNull(e.getMessage(), 'Exception message should not be null');
        }
        Test.stopTest();
    }
}