force-app/main/default/objects/Account/fields/Dangerous_Goods__c.field-meta.xml
<CustomField>
    <fullName>Dangerous_Goods__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dangerous Goods?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pallet_Exchange__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Exchange__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pallet Exchange?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pallet_Jack__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Jack__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pallet Jack?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tail_Lift__c.field-meta.xml
<CustomField>
    <fullName>Tail_Lift__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tail Lift?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Carrier_Score__c/Carrier_Score__c.object-meta.xml
<CustomObject>
    <label>Carrier Score</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carrier Scores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier_Score__c/fields/Availability_Score_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Availability_Score_Percentage__c</fullName>
    <label>Availability Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Carrier_Score__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Carrier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Carrier Scores</relationshipLabel>
    <relationshipName>Carrier_Scores</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Score__c/fields/Lane__c.field-meta.xml
<CustomField>
    <fullName>Lane__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lane</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Carrier Scores</relationshipLabel>
    <relationshipName>Carrier_Scores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Score__c/fields/Price_Level_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Price_Level_Percentage__c</fullName>
    <label>Price Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Carrier_Score__c/fields/Reliability_Score__c.field-meta.xml
<CustomField>
    <fullName>Reliability_Score__c</fullName>
    <label>Reliability Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/Lane_Price__c.object-meta.xml
<CustomObject>
    <label>Lane Price</label>
    <nameField>
        <displayFormat>LP-{0000000}</displayFormat>
        <label>Lane Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lane Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lane_Price__c/fields/Freight_Price__c.field-meta.xml
<CustomField>
    <fullName>Freight_Price__c</fullName>
    <label>€ Lane Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Lane__c.field-meta.xml
<CustomField>
    <fullName>Lane__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lane</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lane Prices</relationshipLabel>
    <relationshipName>Lane_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Price_Request__c.field-meta.xml
<CustomField>
    <fullName>Price_Request__c</fullName>
    <label>Price Request</label>
    <referenceTo>Price_Request__c</referenceTo>
    <relationshipLabel>Lane Prices</relationshipLabel>
    <relationshipName>Lane_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Type_Of_Trailer__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Trailer__c</fullName>
    <label>Type Of Trailer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dual temp</fullName>
            </value>
            <value>
                <fullName>Frigo - ambient</fullName>
            </value>
            <value>
                <fullName>Frigo - chilled</fullName>
            </value>
            <value>
                <fullName>Frigo - frozen</fullName>
            </value>
            <value>
                <fullName>Frigo - split wall</fullName>
            </value>
            <value>
                <fullName>Curtainside - ambient</fullName>
            </value>
            <value>
                <fullName>Box trailer</fullName>
            </value>
            <value>
                <fullName>Cooled</fullName>
                <isActive>false</isActive>
                <label>Cooled</label>
            </value>
            <value>
                <fullName>Dual-temp</fullName>
                <isActive>false</isActive>
                <label>Dual-temp</label>
            </value>
            <value>
                <fullName>Frigo</fullName>
                <isActive>false</isActive>
                <label>Frigo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Request__c/Price_Request__c.object-meta.xml
<CustomObject>
    <label>Price Request</label>
    <nameField>
        <label>Price Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Requests (Account)</relationshipLabel>
    <relationshipName>Price_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Dangerous_Goods__c.field-meta.xml
<CustomField>
    <fullName>Dangerous_Goods__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dangerous Goods</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Loading_Location__c.field-meta.xml
<CustomField>
    <fullName>Loading_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loading Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.Type__c</field>
            <operation>equals</operation>
            <value>Loading</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Price Requests (Loading Location)</relationshipLabel>
    <relationshipName>Loading_Price_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Pallet_exchange__c.field-meta.xml
<CustomField>
    <fullName>Pallet_exchange__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pallet exchange</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Pallet_jack__c.field-meta.xml
<CustomField>
    <fullName>Pallet_jack__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pallet jack</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Price Requests</relationshipLabel>
    <relationshipName>Price_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Tail_lift__c.field-meta.xml
<CustomField>
    <fullName>Tail_lift__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tail lift</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Type_of_trailer__c.field-meta.xml
<CustomField>
    <fullName>Type_of_trailer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Type of trailer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carrier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Carrier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Destination_Location__c.field-meta.xml
<CustomField>
    <fullName>Destination_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.Type__c</field>
            <operation>equals</operation>
            <value>Delivery</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Products (Destination Location)</relationshipLabel>
    <relationshipName>Destinations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Loading_Location__c.field-meta.xml
<CustomField>
    <fullName>Loading_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loading Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.Type__c</field>
            <operation>equals</operation>
            <value>Loading</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Loadings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductLineController.cls
public class ProductLineController {
    
    public class LineInfoAndCarrierScore {
        @AuraEnabled public String Id;
        @AuraEnabled public String productId;
        @AuraEnabled public String productName;
        @AuraEnabled public String carrier;
        @AuraEnabled public String trailerType;
        @AuraEnabled public Decimal unitPrice;
        @AuraEnabled public Decimal dieselMarkup;
        @AuraEnabled public Decimal transitTime;
        @AuraEnabled public Boolean dangerousGoods;
        @AuraEnabled public Boolean palletExchange;
        @AuraEnabled public Boolean tailLift;
        @AuraEnabled public Boolean palletJack;
        @AuraEnabled public List<CarrierScore> carrierScores;
    }

    public class CarrierScore {
        @AuraEnabled public Decimal reliabilityScore;
        @AuraEnabled public Decimal availabilityScore;
        @AuraEnabled public Decimal priceLevel;
    }

    @AuraEnabled(cacheable=true)
    public static List<LineInfoAndCarrierScore> getLinesByLocations(
        String loadingLocationId, 
        String destinationLocationId, 
        Date deliveryDate, 
        String trailerType,
        String seasonId
    ) {
        
        if (String.isBlank(loadingLocationId) || String.isBlank(destinationLocationId)) {
            return new List<LineInfoAndCarrierScore>();
        }

        List<Lane_Price__c> lanePrices = queryLanes(loadingLocationId, destinationLocationId, trailerType, seasonId);
        Map<Id, List<Carrier_Score__c>> carrierToScoreMap = getCarrierScoreMap(lanePrices);
        
        return buildLineInfoList(lanePrices, carrierToScoreMap);
    }

    private static List<Lane_Price__c> queryLanes(String loadingLocationId, String destinationLocationId, String trailerType, String seasonId) {
        List<String> filters = new List<String>();
        filters.add('Freight_Price__c != null');
        filters.add('Type_Of_Trailer__c = :trailerType');
        filters.add('Lane__r.IsActive = true');
        filters.add('Lane__r.Loading_Location__c = :loadingLocationId');
        filters.add('Lane__r.Destination_Location__c = :destinationLocationId');
        filters.add('Price_Request__r.Season__c = :seasonId');

        String query = 'SELECT Id, Freight_Price__c, Lane__c, Type_Of_Trailer__c, Price_Request__c,' +
            ' Lane__r.Name, Lane__r.Loading_Location__c, Lane__r.Destination_Location__c,' +
            ' Price_Request__r.Account__c, Price_Request__r.Account__r.Name, Price_Request__r.Account__r.Dangerous_Goods__c,' +
            ' Price_Request__r.Account__r.Pallet_Exchange__c, Price_Request__r.Account__r.Tail_Lift__c, Price_Request__r.Account__r.Pallet_Jack__c' +
            ' FROM Lane_Price__c WHERE ' + String.join(filters, ' AND ');

        return Database.query(query);
    }

    private static Map<Id, List<Carrier_Score__c>> getCarrierScoreMap(List<Lane_Price__c> lanePrices) {
        Set<Id> carrierIds = extractCarrierIds(lanePrices);

        Map<Id, List<Carrier_Score__c>> carrierToScoreMap = new Map<Id, List<Carrier_Score__c>>();
        for (Carrier_Score__c score : [
            SELECT Id, Carrier__c, Reliability_Score__c, Availability_Score_Percentage__c, Price_Level_Percentage__c
            FROM Carrier_Score__c
            WHERE Carrier__c IN :carrierIds
        ]) {
            if (!carrierToScoreMap.containsKey(score.Carrier__c)) {
                carrierToScoreMap.put(score.Carrier__c, new List<Carrier_Score__c>());
            }
            carrierToScoreMap.get(score.Carrier__c).add(score);
        }

        return carrierToScoreMap;
    }

    private static Set<Id> extractCarrierIds(List<Lane_Price__c> lanePrices) {
        Set<Id> carrierIds = new Set<Id>();
        for (Lane_Price__c lp : lanePrices) {
            if (lp.Price_Request__r.Account__c != null) {
                carrierIds.add(lp.Price_Request__r.Account__c);
            }
        }
        return carrierIds;
    }

    private static List<LineInfoAndCarrierScore> buildLineInfoList(List<Lane_Price__c> lanePrices, Map<Id, List<Carrier_Score__c>> carrierToScoreMap) {
        List<LineInfoAndCarrierScore> result = new List<LineInfoAndCarrierScore>();

        for (Lane_Price__c lp : lanePrices) {
            LineInfoAndCarrierScore lineInfo = createLineInfo(lp, carrierToScoreMap);
            result.add(lineInfo);
        }
        
        return result;
    }

    private static LineInfoAndCarrierScore createLineInfo(Lane_Price__c lp, Map<Id, List<Carrier_Score__c>> carrierToScoreMap) {
        LineInfoAndCarrierScore lineInfo = new LineInfoAndCarrierScore();
        lineInfo.Id = lp.Id;
        lineInfo.productId = lp.Lane__c;
        lineInfo.productName = lp.Lane__r.Name;
        lineInfo.unitPrice = lp.Freight_Price__c;
        lineInfo.trailerType = lp.Type_Of_Trailer__c;
        lineInfo.carrier = lp.Price_Request__r.Account__c != null ? lp.Price_Request__r.Account__r.Name : '';

        lineInfo.dangerousGoods = lp.Price_Request__r.Account__c != null ? lp.Price_Request__r.Account__r.Dangerous_Goods__c : false;
        lineInfo.palletExchange = lp.Price_Request__r.Account__c != null ? lp.Price_Request__r.Account__r.Pallet_Exchange__c : false;
        lineInfo.tailLift = lp.Price_Request__r.Account__c != null ? lp.Price_Request__r.Account__r.Tail_Lift__c : false;
        lineInfo.palletJack = lp.Price_Request__r.Account__c != null ? lp.Price_Request__r.Account__r.Pallet_Jack__c : false;

        lineInfo.carrierScores = buildCarrierScores(lp, carrierToScoreMap);
        
        return lineInfo;
    }

    private static List<CarrierScore> buildCarrierScores(Lane_Price__c lp, Map<Id, List<Carrier_Score__c>> carrierToScoreMap) {
        List<CarrierScore> carrierScores = new List<CarrierScore>();
        List<Carrier_Score__c> scores = carrierToScoreMap.get(lp.Price_Request__r.Account__c);
        
        if (scores != null) {
            for (Carrier_Score__c score : scores) {
                CarrierScore cs = new CarrierScore();
                cs.reliabilityScore = score.Reliability_Score__c;
                cs.availabilityScore = score.Availability_Score_Percentage__c;
                cs.priceLevel = score.Price_Level_Percentage__c;
                carrierScores.add(cs);
            }
        }
        
        return carrierScores;
    }
}