force-app/main/default/objects/Account/fields/Dangerous_Goods__c.field-meta.xml
<CustomField>
    <fullName>Dangerous_Goods__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dangerous Goods?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Destination_Country_Codes__c.field-meta.xml
<CustomField>
    <fullName>Destination_Country_Codes__c</fullName>
    <label>Destination Country Codes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Diesel_mark_up__c.field-meta.xml
<CustomField>
    <fullName>Diesel_mark_up__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Diesel mark-up</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ETS__c.field-meta.xml
<CustomField>
    <fullName>ETS__c</fullName>
    <label>ETS - price p/ton</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fuel_surcharge_percentage__c.field-meta.xml
<CustomField>
    <fullName>Fuel_surcharge_percentage__c</fullName>
    <label>Fuel surcharge percentage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Harbour_Dues__c.field-meta.xml
<CustomField>
    <fullName>Harbour_Dues__c</fullName>
    <label>Harbour Dues - price p/ton</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Overnight_charges__c.field-meta.xml
<CustomField>
    <fullName>Overnight_charges__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Overnight charges</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pallet_Exchange__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Exchange__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pallet Exchange?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pallet_Jack__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Jack__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pallet Jack?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Plug_in__c.field-meta.xml
<CustomField>
    <fullName>Plug_in__c</fullName>
    <label>Plug-in</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Seasonal_Surcharge__c.field-meta.xml
<CustomField>
    <fullName>Seasonal_Surcharge__c</fullName>
    <label>Seasonal Surcharge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tail_Lift__c.field-meta.xml
<CustomField>
    <fullName>Tail_Lift__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tail Lift?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Trailer_Types__c.field-meta.xml
<CustomField>
    <fullName>Trailer_Types__c</fullName>
    <label>Trailer Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dual temp</fullName>
            </value>
            <value>
                <fullName>Frigo - ambient</fullName>
            </value>
            <value>
                <fullName>Frigo - chilled</fullName>
            </value>
            <value>
                <fullName>Frigo - frozen</fullName>
            </value>
            <value>
                <fullName>Frigo - split wall</fullName>
            </value>
            <value>
                <fullName>Curtainside - ambient</fullName>
            </value>
            <value>
                <fullName>Box trailer</fullName>
            </value>
            <value>
                <fullName>Cooled</fullName>
                <isActive>false</isActive>
                <label>Cooled</label>
            </value>
            <value>
                <fullName>Dual-temp</fullName>
                <isActive>false</isActive>
                <label>Dual-temp</label>
            </value>
            <value>
                <fullName>Frigo</fullName>
                <isActive>false</isActive>
                <label>Frigo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Weekend_Charges__c.field-meta.xml
<CustomField>
    <fullName>Weekend_Charges__c</fullName>
    <label>Weekend Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/Lane_Price__c.object-meta.xml
<CustomObject>
    <label>Lane Price</label>
    <nameField>
        <displayFormat>LP-{0000000}</displayFormat>
        <label>Lane Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lane Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lane_Price__c/fields/Additional_Stops__c.field-meta.xml
<CustomField>
    <fullName>Additional_Stops__c</fullName>
    <label>Price Per Stop</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Freight_Price__c.field-meta.xml
<CustomField>
    <fullName>Freight_Price__c</fullName>
    <label>€ Lane Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Lane__c.field-meta.xml
<CustomField>
    <fullName>Lane__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lane</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lane Prices</relationshipLabel>
    <relationshipName>Lane_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mandatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Price_Request__c.field-meta.xml
<CustomField>
    <fullName>Price_Request__c</fullName>
    <label>Price Request</label>
    <referenceTo>Price_Request__c</referenceTo>
    <relationshipLabel>Lane Prices</relationshipLabel>
    <relationshipName>Lane_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Two_Drivers__c.field-meta.xml
<CustomField>
    <fullName>Two_Drivers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Two Drivers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/Price_Request__c.object-meta.xml
<CustomObject>
    <label>Price Request</label>
    <nameField>
        <label>Price Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Requests (Account)</relationshipLabel>
    <relationshipName>Price_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Additional_stops__c.field-meta.xml
<CustomField>
    <fullName>Additional_stops__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Additional stops</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/ADR__c.field-meta.xml
<CustomField>
    <fullName>ADR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ADR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Dangerous_Goods__c.field-meta.xml
<CustomField>
    <fullName>Dangerous_Goods__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dangerous Goods</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Diesel_mark_up__c.field-meta.xml
<CustomField>
    <fullName>Diesel_mark_up__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Diesel mark-up</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Direct_Ferry__c.field-meta.xml
<CustomField>
    <fullName>Direct_Ferry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Direct Ferry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/ETS__c.field-meta.xml
<CustomField>
    <fullName>ETS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ETS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Fuel_surcharge_percentage__c.field-meta.xml
<CustomField>
    <fullName>Fuel_surcharge_percentage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fuel surcharge percentage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Harbour_dues__c.field-meta.xml
<CustomField>
    <fullName>Harbour_dues__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Harbour dues</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Overnight_charges__c.field-meta.xml
<CustomField>
    <fullName>Overnight_charges__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Overnight charges</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Pallet_exchange__c.field-meta.xml
<CustomField>
    <fullName>Pallet_exchange__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pallet exchange</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Pallet_jack__c.field-meta.xml
<CustomField>
    <fullName>Pallet_jack__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pallet jack</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Plug_in__c.field-meta.xml
<CustomField>
    <fullName>Plug_in__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Plug-in</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Price Requests</relationshipLabel>
    <relationshipName>Price_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Seasonal_surcharge__c.field-meta.xml
<CustomField>
    <fullName>Seasonal_surcharge__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seasonal surcharge</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Show_Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Show_Additional_Information__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Data In Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Show_Additional_Lane_Price_Information__c.field-meta.xml
<CustomField>
    <fullName>Show_Additional_Lane_Price_Information__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Show Additional Lane Price Information</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Answer pending</fullName>
            </value>
            <value>
                <fullName>Answer received</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Tail_lift__c.field-meta.xml
<CustomField>
    <fullName>Tail_lift__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tail lift</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Two_drivers__c.field-meta.xml
<CustomField>
    <fullName>Two_drivers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Two drivers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Waiting_hours__c.field-meta.xml
<CustomField>
    <fullName>Waiting_hours__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Waiting hours</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Weekend_charges__c.field-meta.xml
<CustomField>
    <fullName>Weekend_charges__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Weekend charges</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Season__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tender</fullName>
            </value>
            <value>
                <fullName>Spot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Country_ISO_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DK</fullName>
    </customValue>
    <customValue>
        <fullName>GB</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IS</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>GI</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>CY</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>MC</fullName>
    </customValue>
    <customValue>
        <fullName>RS</fullName>
    </customValue>
    <masterLabel>Country ISO Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ClonePriceRequestAction.cls
public with sharing class ClonePriceRequestAction {
    public class Request {
        @InvocableVariable(required=true)
        public Id originalPriceRequestId;

        @InvocableVariable(required=true)
        public Id targetAccountId;

        @InvocableVariable(required=true)
        public List<Id> matchingLanePrices;
    }

    public class Response {
        @InvocableVariable
        public Id clonedPriceRequestId;

        @InvocableVariable
        public String errorMessage;
    }

    @InvocableMethod(label='Clone Price Request Action' description='Clone price request with matching lane prices')
    public static List<Response> createPriceRequest(List<Request> requestList) {
        List<Response> results = new List<Response>();

        if (requestList == null || requestList.isEmpty()) { return results; }

        Request req = requestList[0];
        Response res = new Response();

        try {
            Account targetAccount = getAccount(req.targetAccountId);
            Price_Request__c originalPriceRequest = getPriceRequest(req.originalPriceRequestId);
            Price_Request__c clonedPriceRequest = clonePriceRequest(originalPriceRequest, targetAccount);
            insert clonedPriceRequest;

            res.clonedPriceRequestId = clonedPriceRequest.Id;

            List<Lane_Price__c> lanePrices = getLanePrices(req.matchingLanePrices);

            List<Lane_Price__c> lanePricesToClone = prepareClonedLanePrices(lanePrices, clonedPriceRequest.Id);

            insert lanePricesToClone;

            results.add(res);
        } catch (Exception e) {
            res.errorMessage = e.getMessage();
            results.add(res);
        }
        
        return results;
    }

    private static Account getAccount(Id accountId) {
        return [
            SELECT 
                Id, 
                Name, 
                Destination_Country_Codes__c, 
                Trailer_Types__c 
            FROM Account 
            WHERE Id = :accountId
        ];
    }

    private static Price_Request__c clonePriceRequest(Price_Request__c originalPriceRequest, Account targetAccount) {
        Price_Request__c cloned = originalPriceRequest.clone(false, true, false, false);
        cloned.Name = originalPriceRequest.Season__r?.Name + ' - ' + targetAccount.Name;
        cloned.Account__c = targetAccount.Id;
        cloned.Stage__c = 'Answer pending';
        cloned.Request_Date__c = Date.today();
        return cloned;
    }

    private static List<Lane_Price__c> prepareClonedLanePrices(
        List<Lane_Price__c> lanePrices,
        Id clonedPriceRequestId
    ) {
        List<Lane_Price__c> clonedList = new List<Lane_Price__c>();

        for (Lane_Price__c lanePrice : lanePrices) {
            Lane_Price__c clonedLanePrice = lanePrice.clone(false, true, false, false);
            clonedLanePrice.Price_Request__c = clonedPriceRequestId;
            clonedLanePrice.Freight_Price__c = null;
            clonedList.add(clonedLanePrice);
        }

        return clonedList;
    }

    private static Price_Request__c getPriceRequest(Id priceRequestId) {
        return [
            SELECT 
                Id,
                Request_Date__c,
                CurrencyIsoCode,
                Type__c,
                Account__c,
                ADR__c,
                Season__c,
                Season__r.Name,
                Show_Additional_Information__c,
                Seasonal_surcharge__c,
                Overnight_charges__c,
                Pallet_exchange__c,
                Diesel_mark_up__c,
                Tail_lift__c,
                Additional_stops__c,
                Dangerous_Goods__c,
                ETS__c,
                Show_Additional_Lane_Price_Information__c,
                Plug_in__c,
                Harbour_dues__c,
                Pallet_jack__c,
                Waiting_hours__c,
                Weekend_charges__c,
                Two_drivers__c,
                Direct_Ferry__c,
                Fuel_surcharge_percentage__c 
            FROM Price_Request__c 
            WHERE Id = :priceRequestId 
        ];
    }

    private static List<Lane_Price__c> getLanePrices(List<Id> matchingLanePrices) {
        return [
            SELECT 
                Id, 
                Lane__c,
                CurrencyIsoCode,
                Mandatory__c,
                Price_Request__c,
                Type_Of_Trailer__c, 
                Freight_Price__c
            FROM Lane_Price__c 
            WHERE Id IN :matchingLanePrices
        ];
    }
}