force-app/main/default/objects/Account/fields/Dangerous_Goods_Price__c.field-meta.xml
<CustomField>
    <fullName>Dangerous_Goods_Price__c</fullName>
    <label>Dangerous Goods</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Destination_Country_Codes__c.field-meta.xml
<CustomField>
    <fullName>Destination_Country_Codes__c</fullName>
    <label>Destination Country Codes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Diesel_mark_up_Price__c.field-meta.xml
<CustomField>
    <fullName>Diesel_mark_up_Price__c</fullName>
    <label>Diesel mark-up Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ETS__c.field-meta.xml
<CustomField>
    <fullName>ETS__c</fullName>
    <label>ETS - price p/ton</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fuel_surcharge_percentage__c.field-meta.xml
<CustomField>
    <fullName>Fuel_surcharge_percentage__c</fullName>
    <label>Fuel surcharge percentage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Harbour_Dues__c.field-meta.xml
<CustomField>
    <fullName>Harbour_Dues__c</fullName>
    <label>Harbour Dues - price p/ton</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Overnight_charges_Price__c.field-meta.xml
<CustomField>
    <fullName>Overnight_charges_Price__c</fullName>
    <label>Overnight charges price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pallet_Exchange_Price__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Exchange_Price__c</fullName>
    <label>Pallet Exchange p/pallet</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pallet_Jack_Price__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Jack_Price__c</fullName>
    <label>Pallet Jack</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Plug_in__c.field-meta.xml
<CustomField>
    <fullName>Plug_in__c</fullName>
    <label>Plug-in</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Price_2nd_Driver__c.field-meta.xml
<CustomField>
    <fullName>Price_2nd_Driver__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Two Drivers</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Ferry__c.field-meta.xml
<CustomField>
    <fullName>Price_Ferry__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Direct Ferry</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Per_Stop__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Stop__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Price Per Stop</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Seasonal_Surcharge__c.field-meta.xml
<CustomField>
    <fullName>Seasonal_Surcharge__c</fullName>
    <label>Seasonal Surcharge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tail_Lift_Price__c.field-meta.xml
<CustomField>
    <fullName>Tail_Lift_Price__c</fullName>
    <label>Tail Lift</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Waiting_Hour__c.field-meta.xml
<CustomField>
    <fullName>Waiting_Hour__c</fullName>
    <label>Waiting Costs p/hour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Weekend_Charges__c.field-meta.xml
<CustomField>
    <fullName>Weekend_Charges__c</fullName>
    <label>Weekend Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/Lane_Price__c.object-meta.xml
<CustomObject>
    <label>Lane Price</label>
    <nameField>
        <displayFormat>LP-{0000000}</displayFormat>
        <label>Lane Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lane Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lane_Price__c/fields/Price_2nd_Driver__c.field-meta.xml
<CustomField>
    <fullName>Price_2nd_Driver__c</fullName>
    <label>Price 2nd Driver</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Price_Ferry__c.field-meta.xml
<CustomField>
    <fullName>Price_Ferry__c</fullName>
    <label>Price Ferry</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Price_Request__c.field-meta.xml
<CustomField>
    <fullName>Price_Request__c</fullName>
    <label>Price Request</label>
    <referenceTo>Price_Request__c</referenceTo>
    <relationshipLabel>Lane Prices</relationshipLabel>
    <relationshipName>Lane_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loading</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Request__c.field-meta.xml
<CustomField>
    <fullName>Price_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Request</label>
    <referenceTo>Price_Request__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Preferred_Supplier__c/Preferred_Supplier__c.object-meta.xml
<CustomObject>
    <label>Preferred Supplier</label>
    <nameField>
        <label>Preferred Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferred Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Preferred_Supplier__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Preferred Suppliers</relationshipLabel>
    <relationshipName>Preferred_Suppliers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Preferred_Supplier__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Preferred Suppliers</relationshipLabel>
    <relationshipName>Preferred_Suppliers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/Price_Request__c.object-meta.xml
<CustomObject>
    <label>Price Request</label>
    <nameField>
        <label>Price Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Requests (Account)</relationshipLabel>
    <relationshipName>Price_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/ETS__c.field-meta.xml
<CustomField>
    <fullName>ETS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ETS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Fuel_surcharge_percentage__c.field-meta.xml
<CustomField>
    <fullName>Fuel_surcharge_percentage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fuel surcharge percentage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Harbour_dues__c.field-meta.xml
<CustomField>
    <fullName>Harbour_dues__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Harbour dues</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Loading_Location__c.field-meta.xml
<CustomField>
    <fullName>Loading_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loading Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.Type__c</field>
            <operation>equals</operation>
            <value>Loading</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Price Requests (Loading Location)</relationshipLabel>
    <relationshipName>Loading_Price_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Plug_in__c.field-meta.xml
<CustomField>
    <fullName>Plug_in__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Plug-in</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Date__c</fullName>
    <label>Request Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Price Requests</relationshipLabel>
    <relationshipName>Price_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Seasonal_surcharge__c.field-meta.xml
<CustomField>
    <fullName>Seasonal_surcharge__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seasonal surcharge</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Weekend_charges__c.field-meta.xml
<CustomField>
    <fullName>Weekend_charges__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Weekend charges</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Destination_Location__c.field-meta.xml
<CustomField>
    <fullName>Destination_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.Type__c</field>
            <operation>equals</operation>
            <value>Delivery</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Products (Destination Location)</relationshipLabel>
    <relationshipName>Destinations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Loading_Location__c.field-meta.xml
<CustomField>
    <fullName>Loading_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loading Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.Type__c</field>
            <operation>equals</operation>
            <value>Loading</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Loadings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Season__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tender</fullName>
            </value>
            <value>
                <fullName>Spot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Country_ISO_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DK</fullName>
    </customValue>
    <customValue>
        <fullName>GB</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IS</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>GI</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>CY</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>MC</fullName>
    </customValue>
    <customValue>
        <fullName>RS</fullName>
    </customValue>
    <masterLabel>Country ISO Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LaneSelectorControllerTest.cls
@isTest
private class LaneSelectorControllerTest {
    @TestSetup
    static void setupTestData() {
        
        Account testAccount = new Account(
            Name = 'Test Carrier Account',
            Type = 'Carrier',
            Destination_Country_Codes__c = 'FR;DE;NL',
            Fuel_surcharge_percentage__c = 5.0,
            Diesel_mark_up_Price__c = 10.0,
            ETS__c = 15.0,
            Plug_in__c = 20.0,
            Harbour_Dues__c = 25.0,
            Overnight_charges_Price__c = 45.0,
            Waiting_Hour__c = 30.0,
            Seasonal_Surcharge__c = 40.0,
            Weekend_Charges__c = 35.0,
            Dangerous_Goods_Price__c = 50.0,
            Pallet_Exchange_Price__c = 55.0,
            Tail_Lift_Price__c = 60.0,
            Pallet_Jack_Price__c = 65.0,
            Price_Ferry__c = 70.0,
            Price_2nd_Driver__c = 75.0,
            Price_Per_Stop__c = 80.0
        );
        
        Account testAccount2 = new Account(
            Name = 'Test Carrier Account 2',
            Type = 'Carrier',
            Destination_Country_Codes__c = 'FR;ES;IT',
            Fuel_surcharge_percentage__c = 6.0,
            Price_Per_Stop__c = 85.0
        );
        
        insert new List<Account>{testAccount, testAccount2};
        
        Location__c loadingLocation = new Location__c(
            Name = 'Loading Test Location',
            Type__c = 'Loading',
            Country_Code__c = 'DE',
            Postal_Code__c = '12345'
        );
        
        Location__c deliveryLocation = new Location__c(
            Name = 'Delivery Test Location',
            Type__c = 'Delivery',
            Country_Code__c = 'FR',
            Postal_Code__c = '67890'
        );
        
        insert new List<Location__c>{loadingLocation, deliveryLocation};
        
        Product2 testLane = new Product2(
            Name = 'Test Lane DE-FR',
            Loading_Location__c = loadingLocation.Id,
            Destination_Location__c = deliveryLocation.Id
        );
        insert testLane;

        // Create Tender Season
        Season__c testSeason = new Season__c(
            Name = 'Test Season',
            Type__c = 'Tender',
            Status__c = 'Active',
            Start_Date__c = Date.today().addDays(-30),
            End_Date__c = Date.today().addDays(30)
        );
        
        // Create Spot Season
        Season__c spotSeason = new Season__c(
            Name = 'Spot Season 2025',
            Type__c = 'Spot',
            Status__c = 'Active',
            Start_Date__c = Date.today().addDays(-30),
            End_Date__c = Date.today().addDays(30)
        );
        
        insert new List<Season__c>{testSeason, spotSeason};
        
        Price_Request__c testPriceRequest = new Price_Request__c(
            Account__c = testAccount.Id,
            Request_Date__c = Date.today(),
            Stage__c = 'Answer received',
            Season__c = testSeason.Id,
            Type__c = 'Tender'
        );
        
        Price_Request__c spotPriceRequest = new Price_Request__c(
            Account__c = testAccount.Id,
            Request_Date__c = Date.today(),
            Stage__c = 'Answer received',
            Season__c = spotSeason.Id,
            Type__c = 'Spot'
        );
        
        insert new List<Price_Request__c>{testPriceRequest, spotPriceRequest};
        
        Lane_Price__c testLanePrice = new Lane_Price__c(
            Price_Request__c = testPriceRequest.Id,
            Lane__c = testLane.Id,
            Freight_Price__c = 1000,
            Type_Of_Trailer__c = 'Frigo - chilled',
            Additional_Stops__c = 100,
            Price_2nd_Driver__c = 200,
            Price_Ferry__c = 300,
            PreferredCarrier__c = false
        );
        
        Lane_Price__c spotLanePrice = new Lane_Price__c(
            Price_Request__c = spotPriceRequest.Id,
            Lane__c = testLane.Id,
            Freight_Price__c = 1200,
            Type_Of_Trailer__c = 'Frigo - chilled',
            PreferredCarrier__c = true
        );
        
        insert new List<Lane_Price__c>{testLanePrice, spotLanePrice};

        Carrier_Score__c testCarrierScore = new Carrier_Score__c(
            Carrier__c = testAccount.Id,
            Reliability_Score__c = 95.5,
            Availability_Score_Percentage__c = 88.0,
            Price_Level_Percentage__c = 75.0
        );
        insert testCarrierScore;
        
        // Create opportunity and line item for delete tests
        Opportunity testOpp = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30)
        );
        insert testOpp;
        
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = testLane.Id,
            UnitPrice = 1000,
            IsActive = true
        );
        insert pbe;
        
        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = testOpp.Id,
            PricebookEntryId = pbe.Id,
            Quantity = 1,
            UnitPrice = 1000
        );
        insert oli;
    }

    @isTest
    static void testGetLocationsAndSeasons() {
        Test.startTest();
        List<Location__c> locations = LaneSelectorController.getLocations();
        List<Season__c> seasons = LaneSelectorController.getSeasons();
        List<Season__c> spotSeasons = LaneSelectorController.getSpotSeasons();
        List<Season__c> tenderSeasons = LaneSelectorController.getTenderSeasons();
        Test.stopTest();
        
        Assert.areEqual(2, locations.size(), 'Should return 2 locations');
        Assert.areEqual(2, seasons.size(), 'Should return 2 active seasons');
        Assert.areEqual(1, spotSeasons.size(), 'Should return 1 spot season');
        Assert.areEqual(1, tenderSeasons.size(), 'Should return 1 tender season');
        Assert.areEqual('Active', seasons[0].Status__c, 'Season should be active');
    }

    @isTest
    static void testGetMatchingAccountsAndTrailerTypes() {
        Location__c loadingLocation = [SELECT Id FROM Location__c WHERE Type__c = 'Loading' LIMIT 1];
        Location__c deliveryLocation = [SELECT Id FROM Location__c WHERE Type__c = 'Delivery' LIMIT 1];
        
        Test.startTest();
        List<Account> accounts = LaneSelectorController.getMatchingAccounts(loadingLocation.Id, deliveryLocation.Id);
        List<String> trailerTypes = LaneSelectorController.getTrailerTypePicklistValues();
        Test.stopTest();
        
        Assert.areEqual(2, accounts.size(), 'Should return 2 accounts');
        Assert.isTrue(trailerTypes.size() > 0, 'Should return trailer types');
    }

    @isTest
    static void testGetMatchingLanes() {
        Location__c loadingLocation = [SELECT Id FROM Location__c WHERE Type__c = 'Loading' LIMIT 1];
        Location__c deliveryLocation = [SELECT Id FROM Location__c WHERE Type__c = 'Delivery' LIMIT 1];
        Season__c testSeason = [SELECT Id FROM Season__c WHERE Type__c = 'Tender' LIMIT 1];
        
        Test.startTest();
        List<LaneSelectorController.LaneResult> results = LaneSelectorController.getMatchingLanes(
            loadingLocation.Id, 
            deliveryLocation.Id, 
            testSeason.Id,
            'Frigo - chilled'
        );
        Test.stopTest();
        
        Assert.areEqual(1, results.size(), 'Should return 1 lane result');
        LaneSelectorController.LaneResult result = results[0];
        Assert.isNotNull(result.accountId, 'Account ID should not be null');
        Assert.areEqual('Test Lane DE-FR', result.laneName, 'Lane name should match');
        Assert.areEqual(1, result.trailerTypes.size(), 'Should have 1 trailer type');
        Assert.areEqual(1, result.accountScores.size(), 'Should have 1 account score');
        Assert.areEqual(96, result.accountScores[0].reliabilityScore, 'Reliability score should match');
        Assert.isFalse(result.preferredCarrier, 'Should not be preferred carrier initially');
    }

    @isTest
    static void testCreateAndUpdatePreferredSupplier() {
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Carrier Account' LIMIT 1];
        Lane_Price__c testLanePrice = [SELECT Id FROM Lane_Price__c WHERE Freight_Price__c = 1000 LIMIT 1];
        Location__c loadingLocation = [SELECT Id FROM Location__c WHERE Type__c = 'Loading' LIMIT 1];
        Location__c deliveryLocation = [SELECT Id FROM Location__c WHERE Type__c = 'Delivery' LIMIT 1];
        Season__c testSeason = [SELECT Id FROM Season__c WHERE Type__c = 'Tender' LIMIT 1];
        
        Test.startTest();
        // Create first preferred supplier
        LaneSelectorController.createPreferredSupplier(
            testAccount.Id,
            testLanePrice.Id,
            loadingLocation.Id,
            deliveryLocation.Id,
            'Frigo - chilled',
            1345.5,
            testSeason.Id,
            '{}'
        );
        
        // Create second preferred supplier (should replace first)
        LaneSelectorController.createPreferredSupplier(
            testAccount.Id,
            testLanePrice.Id,
            loadingLocation.Id,
            deliveryLocation.Id,
            'Frigo - chilled',
            1500.0,
            testSeason.Id,
            '{}'
        );
        Test.stopTest();
        
        List<Preferred_Supplier__c> preferredSuppliers = [
            SELECT Id, Total_Freight_Price__c
            FROM Preferred_Supplier__c
            WHERE Account__c = :testAccount.Id
        ];
        
        List<Lane_Price__c> lanePrices = [
            SELECT Id, PreferredCarrier__c
            FROM Lane_Price__c
            WHERE Id = :testLanePrice.Id
        ];
        
        Assert.areEqual(1, preferredSuppliers.size(), 'Should have only 1 preferred supplier');
        Assert.areEqual(1500.0, preferredSuppliers[0].Total_Freight_Price__c, 'Should have updated price');
        Assert.isTrue(lanePrices[0].PreferredCarrier__c, 'Lane price should be marked as preferred');
    }

    @isTest
    static void testCreatePriceRequests() {
        delete [SELECT Id FROM Price_Request__c];
        Account testAccount1 = [SELECT Id, Name FROM Account WHERE Name = 'Test Carrier Account' LIMIT 1];
        Account testAccount2 = [SELECT Id, Name FROM Account WHERE Name = 'Test Carrier Account 2' LIMIT 1];
        Location__c loadingLocation = [SELECT Id FROM Location__c WHERE Type__c = 'Loading' LIMIT 1];
        Location__c deliveryLocation = [SELECT Id FROM Location__c WHERE Type__c = 'Delivery' LIMIT 1];
        Season__c spotSeason = [SELECT Id, Name FROM Season__c WHERE Type__c = 'Spot' LIMIT 1];
        
        List<String> accountIds = new List<String>{testAccount1.Id, testAccount2.Id};
        
        Test.startTest();
        LaneSelectorController.createPriceRequests(
            accountIds,
            spotSeason.Id,
            'Frigo - chilled',
            loadingLocation.Id,
            deliveryLocation.Id
        );
        Test.stopTest();
        
        // Verify Price Requests created
        List<Price_Request__c> createdPriceRequests = [
            SELECT Id, Name, Account__c, Season__c, Type__c, Request_Date__c, Show_Additional_Information__c
            FROM Price_Request__c
            WHERE Account__c IN :accountIds
                AND Season__c = :spotSeason.Id
                AND Type__c = 'Spot'
        ];
        
        Assert.areEqual(2, createdPriceRequests.size(), 'Should create 2 price requests');
        Assert.areEqual(Date.today(), createdPriceRequests[0].Request_Date__c, 'Request date should be today');
        Assert.isTrue(createdPriceRequests[0].Show_Additional_Information__c, 'Should show additional information');
        
        // Verify Lane Prices created
        List<Lane_Price__c> createdLanePrices = [
            SELECT Id, Price_Request__c, Type_Of_Trailer__c, Mandatory__c
            FROM Lane_Price__c
            WHERE Price_Request__c IN :createdPriceRequests
        ];
        
        Assert.areEqual(2, createdLanePrices.size(), 'Should create 2 lane prices');
        Assert.areEqual('Frigo - chilled', createdLanePrices[0].Type_Of_Trailer__c, 'Trailer type should match');
        Assert.isTrue(createdLanePrices[0].Mandatory__c, 'Lane price should be mandatory');
    }

    @isTest
    static void testGetCarriersForSpotPrice() {
        Location__c loadingLocation = [SELECT Id FROM Location__c WHERE Type__c = 'Loading' LIMIT 1];
        Location__c deliveryLocation = [SELECT Id, Country_Code__c FROM Location__c WHERE Type__c = 'Delivery' LIMIT 1];
        Season__c spotSeason = [SELECT Id FROM Season__c WHERE Type__c = 'Spot' LIMIT 1];
        
        Test.startTest();
        LaneSelectorController.SpotPriceResult result = LaneSelectorController.getCarriersForSpotPrice(
            deliveryLocation.Country_Code__c,
            spotSeason.Id,
            'Frigo - chilled',
            loadingLocation.Id,
            deliveryLocation.Id
        );
        Test.stopTest();
        
        // Verify available prices
        Assert.isNotNull(result.availablePrices, 'Available prices should not be null');
        Assert.areEqual(1, result.availablePrices.size(), 'Should return 1 available price');
        
        LaneSelectorController.LaneResult laneResult = result.availablePrices[0];
        Assert.isNotNull(laneResult.accountId, 'Account ID should not be null');
        Assert.areEqual('Test Lane DE-FR', laneResult.laneName, 'Lane name should match');
        Assert.areEqual(1200, laneResult.lanePrice, 'Lane price should be 1200');
        Assert.isTrue(laneResult.preferredCarrier, 'Should be preferred carrier');
        Assert.isNotNull(laneResult.fuelSurchargePercentage, 'Fuel surcharge should not be null');
        Assert.isNotNull(laneResult.pricePerStop, 'Price per stop should not be null');
        
        // Verify potential carriers (carriers without lane prices)
        Assert.isNotNull(result.potentialCarriers, 'Potential carriers should not be null');
        Assert.areEqual(1, result.potentialCarriers.size(), 'Should return 1 potential carrier');
        
        LaneSelectorController.CarrierResult carrierResult = result.potentialCarriers[0];
        Assert.areEqual('Test Carrier Account 2', carrierResult.accountName, 'Carrier name should match');
        Assert.areEqual('Carrier', carrierResult.type, 'Type should be Carrier');
        Assert.isTrue(carrierResult.destinationCountries.contains('FR'), 'Should support FR destination');
    }

    @isTest
    static void testGetCarriersForSpotPriceNoLane() {
        Location__c loadingLocation = new Location__c(
            Name = 'New Loading Location',
            Type__c = 'Loading',
            Country_Code__c = 'ES',
            Postal_Code__c = '28001'
        );
        
        Location__c deliveryLocation = new Location__c(
            Name = 'New Delivery Location',
            Type__c = 'Delivery',
            Country_Code__c = 'IT',
            Postal_Code__c = '00100'
        );
        
        insert new List<Location__c>{loadingLocation, deliveryLocation};
        
        Season__c spotSeason = [SELECT Id FROM Season__c WHERE Type__c = 'Spot' LIMIT 1];
        
        Test.startTest();
        LaneSelectorController.SpotPriceResult result = LaneSelectorController.getCarriersForSpotPrice(
            deliveryLocation.Country_Code__c,
            spotSeason.Id,
            'Frigo - chilled',
            loadingLocation.Id,
            deliveryLocation.Id
        );
        Test.stopTest();
        
        Assert.areEqual(0, result.availablePrices.size(), 'Should return 0 available prices');
        Assert.areEqual(0, result.potentialCarriers.size(), 'Should return 0 potential carriers');
    }

    @isTest
    static void testDeleteLocations() {
        Location__c loadingLocation = [SELECT Id FROM Location__c WHERE Type__c = 'Loading' LIMIT 1];
        Location__c deliveryLocation = [SELECT Id FROM Location__c WHERE Type__c = 'Delivery' LIMIT 1];
        
        // Create additional location without products
        Location__c newLocation = new Location__c(
            Name = 'New Location',
            Type__c = 'Loading',
            Country_Code__c = 'GB',
            Postal_Code__c = '11111'
        );
        insert newLocation;
        
        Test.startTest();
        // Delete loading location with products and opportunity line items
        LaneSelectorController.deleteLocation(loadingLocation.Id, 'Loading');
        // Delete delivery location
        LaneSelectorController.deleteLocation(deliveryLocation.Id, 'Delivery');
        // Delete location without products
        LaneSelectorController.deleteLocation(newLocation.Id, 'Loading');
        Test.stopTest();
        
        List<Location__c> remainingLocations = [SELECT Id FROM Location__c];
        List<Product2> remainingProducts = [SELECT Id FROM Product2];
        List<OpportunityLineItem> remainingOLIs = [SELECT Id FROM OpportunityLineItem];
        
        Assert.areEqual(0, remainingLocations.size(), 'All locations should be deleted');
        Assert.areEqual(0, remainingProducts.size(), 'All products should be deleted');
        Assert.areEqual(0, remainingOLIs.size(), 'All opportunity line items should be deleted');
    }

    @isTest
    static void testGetDeliveryLocations() {
        Test.startTest();
        List<Location__c> deliveryResults = LaneSelectorController.getDeliveryLocations('Delivery', 'Delivery Test');
        List<Location__c> loadingResults = LaneSelectorController.getDeliveryLocations('Loading', 'Loading');
        List<Location__c> noResults = LaneSelectorController.getDeliveryLocations('Loading', 'NonExistent');
        Test.stopTest();
        
        Assert.areEqual(1, deliveryResults.size(), 'Should return 1 delivery location');
        Assert.areEqual(1, loadingResults.size(), 'Should return 1 loading location');
        Assert.areEqual(0, noResults.size(), 'Should return 0 for non-existent');
    }

    @isTest
    static void testExceptionHandling() {
        Test.startTest();
        try {
            LaneSelectorController.deleteLocation(null, 'Loading');
            Assert.fail('Should throw exception for null location');
        } catch (AuraHandledException e) {
            Assert.isNotNull(e.getMessage(), 'Error message should not be null');
        }
        Test.stopTest();
    }

    @isTest
    static void testWrapperClasses() {
        // Test LaneResult
        LaneSelectorController.LaneResult result = new LaneSelectorController.LaneResult();
        result.accountId = 'testId';
        result.laneName = 'Test Lane';
        result.preferredCarrier = true;
        
        // Test TrailerType
        LaneSelectorController.TrailerType trailer = new LaneSelectorController.TrailerType();
        trailer.laneId = 'laneId';
        trailer.type = 'Frigo - chilled';
        trailer.price = 1000.0;
        
        // Test AccountScore
        LaneSelectorController.AccountScore score = new LaneSelectorController.AccountScore();
        score.reliabilityScore = 95.0;
        score.priceScore = 75.0;
        score.availabilityScore = 88.0;
        
        // Test SpotPriceResult
        LaneSelectorController.SpotPriceResult spotResult = new LaneSelectorController.SpotPriceResult();
        spotResult.potentialCarriers = new List<LaneSelectorController.CarrierResult>();
        spotResult.availablePrices = new List<LaneSelectorController.LaneResult>();
        
        // Test CarrierResult
        LaneSelectorController.CarrierResult carrier = new LaneSelectorController.CarrierResult();
        carrier.accountId = 'carrierId';
        carrier.accountName = 'Test Carrier';
        carrier.type = 'Carrier';
        carrier.destinationCountries = 'FR;DE';
        
        Assert.areEqual('testId', result.accountId, 'Account ID should match');
        Assert.isTrue(result.preferredCarrier, 'Should be preferred carrier');
        Assert.areEqual('Frigo - chilled', trailer.type, 'Trailer type should match');
        Assert.areEqual(95.0, score.reliabilityScore, 'Score should match');
        Assert.isNotNull(spotResult.potentialCarriers, 'Potential carriers should not be null');
        Assert.areEqual('Test Carrier', carrier.accountName, 'Carrier name should match');
    }
}