force-app/main/default/objects/Account/fields/Destination_Country_Codes__c.field-meta.xml
<CustomField>
    <fullName>Destination_Country_Codes__c</fullName>
    <label>Destination Country Codes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Country_ISO_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DK</fullName>
    </customValue>
    <customValue>
        <fullName>GB</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IS</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>GI</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>CY</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>MC</fullName>
    </customValue>
    <customValue>
        <fullName>RS</fullName>
    </customValue>
    <masterLabel>Country ISO Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GetAccountDeliveryCountries.cls
public without sharing class GetAccountDeliveryCountries
{
    public class Input {
        @InvocableVariable(required=true)
        public String accountId;
    }

    public class Output {
        @InvocableVariable
        public List<KeyValuePair__mdt> keyValuePairs;
    }

    @InvocableMethod(label='Get Account Delivery Countries' description='Get Account Delivery Countries')
    public static List<Output> getAccountDeliveryCountries(List<Input> inputs)
    {
        List<Output> result = new List<Output>();
        result.add(new Output());
        result[0].keyValuePairs = new List<KeyValuePair__mdt>();

        Account acc = [SELECT Id, Name, Destination_Country_Codes__c FROM Account WHERE Id = :inputs[0].accountId];

        Schema.DescribeFieldResult f = Account.BillingCountryCode.getDescribe();
        for (Schema.PicklistEntry ple : f.getPicklistValues())
        {
            if (acc.Destination_Country_Codes__c.contains(ple.getValue())) {
                result[0].keyValuePairs.add(new KeyValuePair__mdt(MasterLabel = ple.getLabel(), DeveloperName = ple.getValue()));
            }
        }
        return result;
    }
}