force-app/main/default/objects/Account/fields/Destination_Country_Codes__c.field-meta.xml
<CustomField>
    <fullName>Destination_Country_Codes__c</fullName>
    <label>Destination Country Codes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Trailer_Types__c.field-meta.xml
<CustomField>
    <fullName>Trailer_Types__c</fullName>
    <label>Trailer Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dual temp</fullName>
            </value>
            <value>
                <fullName>Frigo - ambient</fullName>
            </value>
            <value>
                <fullName>Frigo - chilled</fullName>
            </value>
            <value>
                <fullName>Frigo - frozen</fullName>
            </value>
            <value>
                <fullName>Frigo - split wall</fullName>
            </value>
            <value>
                <fullName>Curtainside - ambient</fullName>
            </value>
            <value>
                <fullName>Box trailer</fullName>
            </value>
            <value>
                <fullName>Cooled</fullName>
                <isActive>false</isActive>
                <label>Cooled</label>
            </value>
            <value>
                <fullName>Dual-temp</fullName>
                <isActive>false</isActive>
                <label>Dual-temp</label>
            </value>
            <value>
                <fullName>Frigo</fullName>
                <isActive>false</isActive>
                <label>Frigo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lane_Price__c/Lane_Price__c.object-meta.xml
<CustomObject>
    <label>Lane Price</label>
    <nameField>
        <displayFormat>LP-{0000000}</displayFormat>
        <label>Lane Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lane Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lane_Price__c/fields/Lane__c.field-meta.xml
<CustomField>
    <fullName>Lane__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lane</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lane Prices</relationshipLabel>
    <relationshipName>Lane_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mandatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Price_Request__c.field-meta.xml
<CustomField>
    <fullName>Price_Request__c</fullName>
    <label>Price Request</label>
    <referenceTo>Price_Request__c</referenceTo>
    <relationshipLabel>Lane Prices</relationshipLabel>
    <relationshipName>Lane_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Type_Of_Trailer__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Trailer__c</fullName>
    <label>Type Of Trailer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dual temp</fullName>
            </value>
            <value>
                <fullName>Frigo - ambient</fullName>
            </value>
            <value>
                <fullName>Frigo - chilled</fullName>
            </value>
            <value>
                <fullName>Frigo - frozen</fullName>
            </value>
            <value>
                <fullName>Frigo - split wall</fullName>
            </value>
            <value>
                <fullName>Curtainside - ambient</fullName>
            </value>
            <value>
                <fullName>Box trailer</fullName>
            </value>
            <value>
                <fullName>Cooled</fullName>
                <isActive>false</isActive>
                <label>Cooled</label>
            </value>
            <value>
                <fullName>Dual-temp</fullName>
                <isActive>false</isActive>
                <label>Dual-temp</label>
            </value>
            <value>
                <fullName>Frigo</fullName>
                <isActive>false</isActive>
                <label>Frigo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Request__c/Price_Request__c.object-meta.xml
<CustomObject>
    <label>Price Request</label>
    <nameField>
        <label>Price Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Request__c/fields/Type_of_trailer__c.field-meta.xml
<CustomField>
    <fullName>Type_of_trailer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Type of trailer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Destination_Location__c.field-meta.xml
<CustomField>
    <fullName>Destination_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.Type__c</field>
            <operation>equals</operation>
            <value>Delivery</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Products (Destination Location)</relationshipLabel>
    <relationshipName>Destinations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Country_ISO_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DK</fullName>
    </customValue>
    <customValue>
        <fullName>GB</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IS</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>GI</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>CY</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>MC</fullName>
    </customValue>
    <customValue>
        <fullName>RS</fullName>
    </customValue>
    <masterLabel>Country ISO Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FilterPricesToClone.cls
public with sharing class FilterPricesToClone {
    public class Request {
        @InvocableVariable(required=true)
        public Id targetAccountId;

        @InvocableVariable(required=true)
        public Id originalAccountId;

        @InvocableVariable(required=true)
        public Id originalPriceRequestId;
    }

    public class Response {
        @InvocableVariable
        public Integer originalPricesCount;

        @InvocableVariable
        public Integer targetPricesCount;

        @InvocableVariable
        public String originalDestinationCodes;

        @InvocableVariable
        public String originalTrailerTypes;

        @InvocableVariable
        public List<Id> lanePriceIdsForCloning;

    }

    @InvocableMethod(
        label='Filter Prices To Clone Action' 
        description='Filters out irrelevant lane prices based on account settings'
    )
    public static List<Response> filterPrices(List<Request> requestList) {
        List<Response> results = new List<Response>();

        if (requestList == null || requestList.isEmpty()) { return results; }

        Request req = requestList[0];
        Response res = new Response(); 

        List<Lane_Price__c> originalLanePrices = getLanePrices(req.originalPriceRequestId);
        if (originalLanePrices.isEmpty()) { return results; }

        res.originalPricesCount = originalLanePrices.size();
        res.originalTrailerTypes = String.join(getOriginalTrailerTypes(originalLanePrices), ';');
        res.originalDestinationCodes = String.join(getOriginalDestinationCodes(originalLanePrices), ';');

        Account targetAccount = getAccount(req.targetAccountId);
        Account originalAccount = getAccount(req.originalAccountId);
        List<String> targetDestinationCountries = parseMultiSelectPicklist(targetAccount.Destination_Country_Codes__c);
        List<String> targetTrailerTypes = parseMultiSelectPicklist(targetAccount.Trailer_Types__c);

        if (targetDestinationCountries.isEmpty() || targetTrailerTypes.isEmpty()) {return results;}

        List<Id> lanePriceIdsForCloning = getLanePriceIdsForCloning(originalLanePrices, targetDestinationCountries, targetTrailerTypes);

        res.targetPricesCount = lanePriceIdsForCloning.size();
        res.lanePriceIdsForCloning = lanePriceIdsForCloning;
        results.add(res);
        
        return results;
    }

    private static List<Lane_Price__c> getLanePrices(Id priceRequestId) {
        return [
            SELECT 
                Id, 
                Lane__c,
                CurrencyIsoCode,
                Mandatory__c,
                Type_Of_Trailer__c, 
                Lane__r.Destination_Location__r.Country_Code__c 
            FROM Lane_Price__c 
            WHERE Price_Request__c = :priceRequestId
        ];
    }

    private static Set<String> getOriginalTrailerTypes(List<Lane_Price__c> originalLanePrices) {
        Set<String> result = new Set<String>();
        for (Lane_Price__c lanePrice : originalLanePrices) {
            result.add(lanePrice.Type_Of_Trailer__c);
        }
        return result;
    }

    private static Set<String> getOriginalDestinationCodes(List<Lane_Price__c> originalLanePrices) {
        Set<String> result = new Set<String>();
        for (Lane_Price__c lanePrice : originalLanePrices) {
            result.add(lanePrice.Lane__r?.Destination_Location__r?.Country_Code__c);
        }
        return result;
    }

    private static Account getAccount(Id accountId) {
        return [
            SELECT 
                Id, 
                Name, 
                Trailer_Types__c,
                Destination_Country_Codes__c 
            FROM Account 
            WHERE Id = :accountId
        ];
    }

    private static List<String> parseMultiSelectPicklist(String picklistValue) {
        return String.isBlank(picklistValue) 
            ? new List<String>() 
            : picklistValue.split(';');
    }

    private static List<Id> getLanePriceIdsForCloning(
        List<Lane_Price__c> originalLanePrices,
        List<String> targetDestinationCountries,
        List<String> targetTrailerTypes
    ) {
        List<Id> result = new List<Id>();

        for (Lane_Price__c lanePrice : originalLanePrices) {
            if (
                targetDestinationCountries.contains(lanePrice.Lane__r?.Destination_Location__r?.Country_Code__c) &&
                targetTrailerTypes.contains(lanePrice.Type_Of_Trailer__c)
            ) {
                result.add(lanePrice.Id);
            }
        }

        return result;
    }
}