force-app/main/default/objects/Account/fields/Destination_Country_Codes__c.field-meta.xml
<CustomField>
    <fullName>Destination_Country_Codes__c</fullName>
    <label>Destination Country Codes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Trailer_Types__c.field-meta.xml
<CustomField>
    <fullName>Trailer_Types__c</fullName>
    <label>Trailer Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dual temp</fullName>
            </value>
            <value>
                <fullName>Frigo - ambient</fullName>
            </value>
            <value>
                <fullName>Frigo - chilled</fullName>
            </value>
            <value>
                <fullName>Frigo - frozen</fullName>
            </value>
            <value>
                <fullName>Frigo - split wall</fullName>
            </value>
            <value>
                <fullName>Curtainside - ambient</fullName>
            </value>
            <value>
                <fullName>Box trailer</fullName>
            </value>
            <value>
                <fullName>Cooled</fullName>
                <isActive>false</isActive>
                <label>Cooled</label>
            </value>
            <value>
                <fullName>Dual-temp</fullName>
                <isActive>false</isActive>
                <label>Dual-temp</label>
            </value>
            <value>
                <fullName>Frigo</fullName>
                <isActive>false</isActive>
                <label>Frigo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lane_Price__c/Lane_Price__c.object-meta.xml
<CustomObject>
    <label>Lane Price</label>
    <nameField>
        <displayFormat>LP-{0000000}</displayFormat>
        <label>Lane Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lane Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lane_Price__c/fields/Lane__c.field-meta.xml
<CustomField>
    <fullName>Lane__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lane</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lane Prices</relationshipLabel>
    <relationshipName>Lane_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Loading_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Loading_Country_Code__c</fullName>
    <formula>Lane__r.Loading_Location__r.Country_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loading Country Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Price_Request__c.field-meta.xml
<CustomField>
    <fullName>Price_Request__c</fullName>
    <label>Price Request</label>
    <referenceTo>Price_Request__c</referenceTo>
    <relationshipLabel>Lane Prices</relationshipLabel>
    <relationshipName>Lane_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lane_Price__c/fields/Type_Of_Trailer__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Trailer__c</fullName>
    <label>Type Of Trailer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dual temp</fullName>
            </value>
            <value>
                <fullName>Frigo - ambient</fullName>
            </value>
            <value>
                <fullName>Frigo - chilled</fullName>
            </value>
            <value>
                <fullName>Frigo - frozen</fullName>
            </value>
            <value>
                <fullName>Frigo - split wall</fullName>
            </value>
            <value>
                <fullName>Curtainside - ambient</fullName>
            </value>
            <value>
                <fullName>Box trailer</fullName>
            </value>
            <value>
                <fullName>Cooled</fullName>
                <isActive>false</isActive>
                <label>Cooled</label>
            </value>
            <value>
                <fullName>Dual-temp</fullName>
                <isActive>false</isActive>
                <label>Dual-temp</label>
            </value>
            <value>
                <fullName>Frigo</fullName>
                <isActive>false</isActive>
                <label>Frigo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Request__c/Price_Request__c.object-meta.xml
<CustomObject>
    <label>Price Request</label>
    <nameField>
        <label>Price Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Cascade</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Requests (Account)</relationshipLabel>
    <relationshipName>Price_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Loading_Location__c.field-meta.xml
<CustomField>
    <fullName>Loading_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loading Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.Type__c</field>
            <operation>equals</operation>
            <value>Loading</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Price Requests (Loading Location)</relationshipLabel>
    <relationshipName>Loading_Price_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Request__c/fields/Type_of_trailer__c.field-meta.xml
<CustomField>
    <fullName>Type_of_trailer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Type of trailer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Destination_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Destination_Country_Code__c</fullName>
    <formula>Destination_Location__r.Country_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Destination Country Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Destination_Location__c.field-meta.xml
<CustomField>
    <fullName>Destination_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.Type__c</field>
            <operation>equals</operation>
            <value>Delivery</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Products (Destination Location)</relationshipLabel>
    <relationshipName>Destinations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Loading_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Loading_Country_Code__c</fullName>
    <formula>Loading_Location__r.Country_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loading Country Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Loading_Location__c.field-meta.xml
<CustomField>
    <fullName>Loading_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loading Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location__c.Type__c</field>
            <operation>equals</operation>
            <value>Loading</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Loadings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Country_ISO_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DK</fullName>
    </customValue>
    <customValue>
        <fullName>GB</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IS</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>GR</fullName>
    </customValue>
    <customValue>
        <fullName>IE</fullName>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>GI</fullName>
    </customValue>
    <customValue>
        <fullName>SE</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>LT</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>CY</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>MC</fullName>
    </customValue>
    <customValue>
        <fullName>RS</fullName>
    </customValue>
    <masterLabel>Country ISO Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TPQGetLanesToAddInPriceRequest.cls
public with sharing class TPQGetLanesToAddInPriceRequest {
    private static final String DELIMITER = ';';
    public class Input {
        @InvocableVariable(required=true)
        public Id priceRequestId;

        @InvocableVariable(required=true)
        public List<String> loadingCountryCodes;

        @InvocableVariable(required=true)
        public List<String> deliveryCountryCodes;
    }

    public class Response {
        @InvocableVariable
        public List<Product2> matchingLanes;
    }

    @InvocableMethod(label='TPQ Get Lanes To Add In Price Request' description='TPQ Get Lanes To Add In Price Request')
    public static List<Response> addLanesToPriceRequest(List<Input> inputs) {
        List<Response> results = new List<Response>();

        if (inputs == null || inputs.isEmpty()) {
            System.debug(LoggingLevel.ERROR, 'No input data provided to run TPQ Get Lanes To Add In Price Request');
            return results;
        }

        try {
            Id priceRequestId = inputs[0].priceRequestId;

            List<String> loadingCountryCodes = parseCountryCodes(inputs[0].loadingCountryCodes);
            List<String> deliveryCountryCodes = parseCountryCodes(inputs[0].deliveryCountryCodes);

            Price_Request__c priceRequest = [SELECT Id, Account__r.Trailer_Types__c, Account__r.Destination_Country_Codes__c FROM Price_Request__c WHERE Id = :priceRequestId];
            List<Lane_Price__c> existingLanePrices = [SELECT Id, Lane__c, Type_Of_Trailer__c FROM Lane_Price__c WHERE Price_Request__c = :priceRequestId];

            List<String> accountDestinationCodes = priceRequest.Account__r.Destination_Country_Codes__c.split(';');
            List<Id> existingLaneIds = new List<Id>();
            for (Lane_Price__c lp : existingLanePrices) {
                existingLaneIds.add(lp.Lane__c);
            }

            List<Product2> lanes = [
                SELECT Id, Name, Loading_Country_Code__c, Destination_Country_Code__c
                FROM Product2 
                WHERE Id NOT IN :existingLaneIds 
                    AND Destination_Location__r.Country_Code__c IN :deliveryCountryCodes
                    AND Loading_Location__r.Country_Code__c IN :loadingCountryCodes
            ];

            Response res = new Response();
            res.matchingLanes = lanes;
            results.add(res);

        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, 'Error in TPQ Get Lanes To Add In Price Request: ' + e.getMessage());
            throw e;
        }
        return results;
    }

    @TestVisible
    private static List<String> parseCountryCodes(List<String> countryCodes) {
        List<String> parsedCodes = new List<String>();
        
        if (countryCodes == null) { return parsedCodes; }
        
        for (String str : countryCodes) {
            if (String.isNotBlank(str)) {
                for (String code : str.split(DELIMITER)) {
                    String cleanCode = code.trim();
                    if (String.isNotBlank(cleanCode)) {
                        parsedCodes.add(cleanCode);
                    }
                }
            }
        }
    
        return parsedCodes;
    }
}