force-app/main/default/objects/Account/fields/Trailer_Types__c.field-meta.xml
<CustomField>
    <fullName>Trailer_Types__c</fullName>
    <label>Trailer Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dual temp</fullName>
            </value>
            <value>
                <fullName>Frigo - ambient</fullName>
            </value>
            <value>
                <fullName>Frigo - chilled</fullName>
            </value>
            <value>
                <fullName>Frigo - frozen</fullName>
            </value>
            <value>
                <fullName>Frigo - split wall</fullName>
            </value>
            <value>
                <fullName>Curtainside - ambient</fullName>
            </value>
            <value>
                <fullName>Box trailer</fullName>
            </value>
            <value>
                <fullName>Cooled</fullName>
                <isActive>false</isActive>
                <label>Cooled</label>
            </value>
            <value>
                <fullName>Dual-temp</fullName>
                <isActive>false</isActive>
                <label>Dual-temp</label>
            </value>
            <value>
                <fullName>Frigo</fullName>
                <isActive>false</isActive>
                <label>Frigo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GetAllAccountTrailerTypes.cls
public without sharing class GetAllAccountTrailerTypes {

    public class Output {
        @InvocableVariable
        public List<KeyValuePair__mdt> keyValuePairs;
    }

    @InvocableMethod(label='Get All Account Trailer Types' description='Get All Account Trailer Types')
    public static List<Output> getAccountTrailerTypes()
    {
        List<Output> result = new List<Output>();
        result.add(new Output());
        result[0].keyValuePairs = new List<KeyValuePair__mdt>();


        Schema.DescribeFieldResult f = Account.Trailer_Types__c.getDescribe();
        for (Schema.PicklistEntry ple : f.getPicklistValues())
        {
            result[0].keyValuePairs.add(new KeyValuePair__mdt(MasterLabel = ple.getLabel(), DeveloperName = ple.getValue()));
        }
        return result;
    }
}